const books = [
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    description: "A novel about wealth, love, and the American dream.",
    category: "Fiction",
    format: "Paperback",
    availableCopies: 5,
  },
  {
    title: "1984",
    author: "George Orwell",
    description: "A dystopian novel about surveillance and totalitarianism.",
    category: "Fiction",
    format: "Paperback",
    availableCopies: 4,
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    description: "A story about justice, morality, and childhood.",
    category: "Fiction",
    format: "Hardcover",
    availableCopies: 3,
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    description: "A classic novel about relationships, society, and marriage.",
    category: "Fiction",
    format: "Paperback",
    availableCopies: 6,
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    description: "A fantasy adventure following Bilbo Baggins.",
    category: "Fiction",
    format: "Hardcover",
    availableCopies: 4,
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    description: "A practical guide to building better habits.",
    category: "Non-Fiction",
    format: "Paperback",
    availableCopies: 5,
  },
  {
    title: "Sapiens",
    author: "Yuval Noah Harari",
    description: "A brief history of humankind.",
    category: "Non-Fiction",
    format: "Hardcover",
    availableCopies: 3,
  },
  {
    title: "The Power of Now",
    author: "Eckhart Tolle",
    description: "A guide to mindfulness and living in the present.",
    category: "Non-Fiction",
    format: "Paperback",
    availableCopies: 4,
  },
  {
    title: "Educated",
    author: "Tara Westover",
    description: "A memoir about education, family, and personal growth.",
    category: "Non-Fiction",
    format: "Paperback",
    availableCopies: 3,
  },
  {
    title: "Steve Jobs",
    author: "Walter Isaacson",
    description: "A biography of Apple co-founder Steve Jobs.",
    category: "Non-Fiction",
    format: "Hardcover",
    availableCopies: 2,
  },
  {
    title: "Clean Code",
    author: "Robert C. Martin",
    description: "A guide to writing clean and maintainable software.",
    category: "Academic",
    format: "Paperback",
    availableCopies: 5,
  },
  {
    title: "Design Patterns",
    author: "Erich Gamma",
    description: "Fundamental reusable solutions for software design.",
    category: "Academic",
    format: "Hardcover",
    availableCopies: 3,
  },
  {
    title: "Computer Networking",
    author: "Andrew S. Tanenbaum",
    description: "An introduction to computer networking concepts.",
    category: "Academic",
    format: "Paperback",
    availableCopies: 4,
  },
  {
    title: "Database System Concepts",
    author: "Abraham Silberschatz",
    description: "A comprehensive introduction to database systems.",
    category: "Academic",
    format: "Paperback",
    availableCopies: 3,
  },
  {
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen",
    description: "A comprehensive textbook covering algorithms and data structures.",
    category: "Academic",
    format: "Hardcover",
    availableCopies: 2,
  },
  {
    title: "Spider-Man",
    author: "Stan Lee",
    description: "A classic superhero comic featuring Spider-Man.",
    category: "Comics",
    format: "Paperback",
    availableCopies: 5,
  },
  {
    title: "Batman: Year One",
    author: "Frank Miller",
    description: "A comic exploring Batman's early days as a crime fighter.",
    category: "Comics",
    format: "Hardcover",
    availableCopies: 3,
  },
  {
    title: "The Avengers",
    author: "Stan Lee",
    description: "A superhero comic featuring the Avengers team.",
    category: "Comics",
    format: "Paperback",
    availableCopies: 4,
  },
  {
    title: "Watchmen",
    author: "Alan Moore",
    description: "A graphic novel exploring superheroes and society.",
    category: "Comics",
    format: "Hardcover",
    availableCopies: 2,
  },
  {
    title: "Maus",
    author: "Art Spiegelman",
    description: "A graphic novel telling a story of survival and family.",
    category: "Comics",
    format: "Paperback",
    availableCopies: 3,
  },
];

module.exports = books;